### ISSUE TITLE
Minor Broken Icon and Suggestion for Links under Communication

### ISSUE THREAD

**Issue by meganjro** [andreashandel/MADAcourse#11]
Hi Dr. Handel,

Under module 5c: Data Import to R, the emoji icon is not working.

I found it very hard to find anything typo-wise. I think this course website is very nicely laid out and easily navigable. As a student, I always appreciate having all the information at my fingertips.

My only suggestion: Would it be overkill to maybe add actual links under the Communications section to UGA ELC and the class GitHub? It would be nice to just have a quick link to these since I often switch computers. 

Also I know this should probably go under the Project discussion board, but since I'm assuming other classmates will look at these issues too, will you be expanding the Project information at all? I'm assuming for Part 1, we submit the data we chose to our new project directory, but it would be nice to have that clarified on the 5c assessment page.

Thank you!

Megan Robertson

**Comment by andreashandel** [comment]
Thanks, I fixed the emoticon.

I understand why links to eLC/Github would be good. While I agree, I made the conscious decision not to include them. I'm trying to create the course website as "stand-alone" and independent of the UGA course as possible so the general public (e.g. other students) can easily use the material. Because of that, I'm trying to minimize anything on the website that is too tightly integrated and specific for this particular instance of the course. Your best bet is probably to bookmark eLC and the github class (which is what I do, and with modern browsers your bookmarks should sync between computers. I constantly switch between 4 different ones and the bookmarks come along).

I wasn't going to post more about the project, but it you have specific questions, go ahead and ask them (preferably on eLC). You don't yet need to post the data for part 1, just describe it. But of course if you can post it and describe it using the actual data, that is best.
