### ISSUE TITLE
Beaudry_Typo,Suggestion,Website_Issues

### ISSUE THREAD

**Issue by MeganSarah** [andreashandel/MADAcourse#12]
Hello,

I went to find some typos in The Art of Data Science. I found a typo in section 2. 6 Applying the Epicycle of Analysis Process. At the end of the second sentence they have a space between “are” and the colon. There should not be a space here. 

In terms of suggestions for improving this course, I snuck ahead to section 5a – Types of Data. You went over two kinds of variables that are common: quantitative and qualitative. I would suggest that you also formally introduce the concept of “mixed-methods.” Although I have yet to do a mixed-methods study myself, they are fairly common and important to public health. I have listed below several articles I think that may work as reading example of these types of studies, if you had decided to include this concept in your course. 
1.	Creswell JW, Fetters MD, Ivankova NY. Designing a mixed methods study in primary care. Annals of Family Medicine 2004;2:7-12
2.	Mumtaz, Z, Nykiforuk, C, Bhatti A, Ataullahjan A, Salway S. The role of social geography on Lady Health Workers’ mobility and effectiveness in Pakistan. Social Science and Medicine 2013: 91:48-57.
3.	Mumtaz Z, Cutherell, A and Bhatti, A. Saving mothers and newborns in communities: strengthening community midwives to provide high quality essential newborn and maternal care in Baluchistan, Pakistan in a financially sustainable manner. BMC Pregnancy and Childbirth 2014;14:131
You’ll note that two of the papers are by the same first author. She was a guest lecturer in a course I took on the foundation of public health research for my MS, and was expert on (you guessed it) mixed methods research!

Also, I am not sure if this is an issue on my end (as I have been having computer problems lately) but the top of the pages to some of the modules (i.e., all of module 4 and 5)  are covered by the course menu….

Thank you,
Megan Beaudry

**Comment by andreashandel** [comment]
Thanks.
I can't do anything about the typo in Art of Data Science, you would have to file that with the authors :) 

While mixed-methods are certainly an interesting approach, within such a study every variable that is collected is either qualitative or quantitative. As such, mixed-methods is not a new type of variable, it's just an approach that combines both types in a single study. In fact, this is very commmon since many studies record some qualitative variables (e.g. race) though the mixed-methods terminology is usually applied to an approach where the qualitative data is 'free text'. The course currently doesn't talk about study types, so I'm not sure where I would include mixed-methods, but if I discuss study types at some point I'll make sure to mention them.

@alblubaugh mentioned such a problem with the menu covering the first line of text when the browser window is at a specific size. Does yours look like the screenshot in issue #9? If yes, that was/is a problem of the way RStudio/Github apply the layout formatting, unfortunately nothing I can fix (without  a lot of work). If yours is different, maybe open a new issue and post a screenshot so I can see the problem.
