### ISSUE TITLE
Top of page doesn't show when using half screen view (Amanda Blubaugh- GitHub Issues Exercise) 

### ISSUE THREAD

**Issue by alblubaugh** [andreashandel/MADAcourse#9]
Greetings,

I have found that when looking at the modules, it is easiest for me to have the website with the module open on half of the screen and have R studio or the recommended reading on the opposite half of the screen.  

Only when the screen is halved, the very top of each module is no longer visible and is covered by the navigation bar on the top.  When the page is open full screen it isn't an issue. I am not sure how to resolve this.  Could it just be my browser?  I mainly use Chrome.

Best,

Amanda Blubaugh

**Comment by alblubaugh** [comment]
![scrnshot_webpageDisplay](https://user-images.githubusercontent.com/42119999/63893845-319cc080-c9b9-11e9-8b75-c1eb64cf42a0.jpg)
 
I have attached a picture to try and clarify. I think you are correct about a format feature and changing it via the CSS style sheet. If I move the division between the two screens to expand the web page, the navigation banner becomes thinner and fits both the MADA header and course navigation links in one row, allowing the top of the table of contents and header for the page to become fully visible under the navigation bar.

This was not a major problem at all: the website has been easy to navigate and has been helpful while moving through the exercises and modules, so it was hard to come up with an issue. :)

**Comment by andreashandel** [comment]
Thanks, I understand now, and I was able to reproduce it. This is clearly a bug in the layout. A quick fix I could try is to switch the layout theme. Those themes are all from the bootswatch CSS library and I'm currently using one called cerulean. I could see if another theme might not have that bug. However, switching the layout might be confusing to students, so for now I'm leaving it as is since it seems to not be a major problem.
